FROM python:3.13-slim

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /app

# Install dependencies
# We use --system to install into the system python environment since we are in a container
RUN uv pip install --system requests beautifulsoup4 pdfplumber schedule

COPY scraper/scraper.py .

CMD ["python", "scraper.py"]
